#ifndef QUIZ_H_INCLUDED
#define QUIZ_H_INCLUDED

#include <iostream>
#include <stdlib.h>
#include <fstream>
#include <sstream>
#include <string.h>
#include <vector>
#include <iomanip>
#include <ctime>
#include <time.h>
#include <algorithm>    // needed for random_shuffle
#include "user.h"

#define TRUE 1
#define FALSE 0

using namespace std;

class QuizAttempt;
class Question;

class too_few_questions {};


//! A standalone function to get the current date as a string.
/*!
		Returns current date in format DD-MM-YYYY.
        Gotten from http://stackoverflow.com/questions/997946/how-to-get-current-time-and-date-in-c
*/
string currentDate(void);


//! A standalone function to fill up the questionBank.
/*!
		Encrypts the password by modifying each character in the string, as well as adding extra characters.
*/
int fillQuestionBank(void);


//! QuizAttempt class
/********************************************//**
Class for a QuizAttempt. Is generated by a student taking a quiz.
***********************************************/
class QuizAttempt
{
  public:

    //! Constructor used to generate a QuizAttempt.
    /*!
        \param *student pointer to the student taking the quiz.
    */
    QuizAttempt(StudentUser *student_user);

    //! Member function which asks the student all 10 questions and records the student's answers.
    /*!

    */
    void runQuiz(void);

    //! Member function which adds 10 random questions from the questionBank vector.
    /*!

    */
    void getQuestions(void);

    //! A member function to save the quiz result to the student's profile.
    /*!

    */
    void saveResultToProfile(void);

  protected:
    //! Pointer to the user taking the quiz.
    StudentUser *student_user;
    //! Vector of pointers to questions.
    vector<Question*> quizQuestions;
    //! Number of questions answered correctly.
    int correctAnswers;
};


//! Question class
/********************************************//**
Class for a Question to be used during a QuizAttempt.
***********************************************/
class Question
{
  public:

    //! Constructor used to generate a Question in memory.
    /*!
        \param questionString the text of the question.
        \param correctAnswer Index letter of the correct answer inside of the answerChoice vector.
    */
    Question(string questionString, char correctAnswer):
        questionString(questionString), correctAnswer(correctAnswer){}

    //! A member function to add an answerChoice to the question.
    /*!
        \param answer the possible answer to be added.
    */
    void addAnswerChoice(string answer);

    //! A member function used during a QuizAttempt to ask the student this question.
    /*!

    */
    void askQuestion(void);

    //! A member function to check if the answer chosen is correct.
    /*!
        \param answerInput the index number of the answer to check.
        \return TRUE if the answer is correct, FALSE if it is incorrect.
    */
    bool checkAnswer(char answerInput);

  protected:
    //! The actual question.
    string questionString;
    //! Vector of possible answers to the question.
    vector<string> answerChoice;
    //! Index number of correct answer inside answerString[].
    char correctAnswer;
};


#endif // QUIZ_H_INCLUDED
