#include <iostream>
#include <fstream>
#include <sstream>
#include <string.h>
#include <vector>
using namespace std;

class User;
class StudentUser;
class AdminUser;
class QuizResult;
class QuizAttempt;
class QuestionBank;
class Question;


//! Base User class
/********************************************//**
Abstract base class User, to be used to implement different types of users.
***********************************************/
class User
{
	public:

		//! A constructor for creating a new User with the provided userID.
		/*!
				\param ID a string containing the User's ID.
		*/
		StudentProfile(string ID)
		{
			userID = ID;
		}

		//! A pure virtual member function to view the profile of a User.
		/*!

		*/
		virtual StudentProfile viewProfile() = 0;

	protected:
		//! User ID variable.
		string userID=0;
		//! User permission level (higher = more permissions).
		char permissionLevel=0;
};

//! StudentUser class
/********************************************//**
Class for a StudentUser, which is created by a User logging in with student credentials.
***********************************************/
class StudentUser: public User
{
  public:

	  //! StudentUser constructor for students after logging in.
		/*!
	      \param ID a string containing the StudentUser's ID.
		*/
		StudentUser(string ID)
		{
			User(ID);
			permissionLevel=1;
			profile = new StudentProfile(ID);
		}

		//! A member function to attempt a quiz.
		/*!

		*/
    void takeQuiz()
    {

    }


  protected:
    //! Student's profile containing previous quiz results.
		StudentProfile profile=0;
};

//! AdminUser class
/********************************************//**
Class for a AdminUser, which is created by a User logging in with admin credentials.
***********************************************/
class AdminUser: public User
{
  public:

	  //! AdminUser constructor for admins after logging in.
		/*!
	      \param ID a string containing the AdminUser's ID.
		*/
		AdminUser(string ID)
		{
			User(ID);
			permissionLevel=2;
		}

		//! A member function to view the profile of a student.
		/*!
				\param ID a string containing the ID of the student whose profile is desired.
		*/
		void viewProfile(string studentID)
		{
			profileFileName = "data\\profiles\\" + studentID + ".txt";

			ifstream input(profileFileName.c_str());

			cout << "Student ID: " << studentID << endl;

	    if(input.is_open())
	    {
        cout << input.rdbuf();
        input.close();
	    }
			else
			{
				cout << "ERROR: There is no profile for that student.\n";
			}
		}
};

//! StudentProfile class
/********************************************//**
Class for a StudentProfile, which is a log of all quiz results for a particular student.
***********************************************/
class StudentProfile
{
  public:

		//! StudentProfile constructor for initialisation.
		/*!
	      \param ID a string containing the StudentUser's ID.
		*/
		StudentProfile(string ID)
		{
			studentID = ID;
			profileFileName = "data\\profiles\\" + ID + ".txt";
		}

    //! A member function to add a QuizResult from a quiz attempt.
		/*!
		    \param *result a pointer to the QuizResult to add.
		*/
    void addResult(QuizResult *result)
    {
			//results.push_back(result);

			ofstream output(profileFileName.c_str(), std::ofstream::app);

      output << std::setw(15) << std::left << "Date of quiz: " << result->dateOfQuiz << endl;
			output << std::setw(15) << std::left << "Result: " << result->correctAnswers << "/10\n";

      output.close();
    }

    //! A member function to print a profile to the screen.
		/*!

		*/
    void printToScreen()
    {
			ifstream input(profileFileName.c_str());

			cout << "Student ID: " << studentID << endl;

	    if(input.is_open())
	    {
        cout << input.rdbuf();
        input.close();
	    }
    }

		//! A member function to print a profile to a specified file.
		/*!
		    \param &output a pointer to the output file stream to print to.
		*/
    void printToFile(ofstream &output)
    {
			output << "Student: " << ID << endl;
			for(int i=0; i<results.size(); i++)
			{
				//TODO: output << results[i]
			}
    }

  protected:

		//! ID of StudentUser which owns the profile.
    string studentID=0;
		//! Name of file which stores the profile.
    string profileFileName=0;
};

//! QuizResult class
/********************************************//**
Class for a QuizResult. Is generated by a QuizAttempt, and saved to a StudentProfile.
***********************************************/
class QuizResult
{
  public:

		//! Constructor used to generate a QuizResult.
		/*!
				\param dateOfQuiz the date the quiz was taken.
				\param answers Number of correct answers during the quiz.
		*/
		QuizResult(string dateOfQuiz, int correctAnswers):
			dateOfQuiz(dateOfQuiz), correctAnswers(correctAnswers){}

		//! The date the quiz was taken.
		string dateOfQuiz;
		//! Number of correct answers during the quiz.
		int correctAnswers;
};


int main(void)
{
	return 0;
}

//! A function to login as a User.
/*!
		\param ID a string of the desired ID.
		\param password a string containing the User's corresponding password.
*/
bool login(string ID,string password)
{
	//TODO: scan credentials to check if legit
}

/*
Name:   file_copy_buff
Arg1:   Reference to name of input file to open.
Arg2:   Reference to already opened output stream.
Uses rdbuf(), which returns a pointer to input's stream buffer, and prints
out the contents of the input file to the output file. This method does not
need any temporary strings or chars to hold the contents before printing to
the output file.
-------------------------------------------------------------------------*/
void file_copy_buff(const string &name, ofstream &output)
{
    ifstream input(name.c_str());

    if(input.is_open())
    {
        output << input.rdbuf();
        input.close();
        cout << name << " added to output successfully.\n\n\n";
    }
    else
    {
        throw bad_file();
    }
}
