#include <iostream>
#include <fstream>
#include <sstream>
#include <string.h>
#include <vector>
#include <iomanip>

using namespace std;

class QuizResult;
class QuizAttempt;
class QuestionBank;
class Question;


enum{ERROR,ID_NOT_FOUND,WRONG_PASS,STUDENT,ADMIN};

#include "user.h"

//! QuizResult class
/********************************************//**
Class for a QuizResult. Is generated by a QuizAttempt, and saved to a StudentProfile.
***********************************************/
class QuizResult
{
  public:

    //! Constructor used to generate a QuizResult.
    /*!
        \param dateOfQuiz the date the quiz was taken.
        \param correctAnswers Number of correct answers during the quiz.
    */
    QuizResult(string dateOfQuiz, int correctAnswers):
        dateOfQuiz(dateOfQuiz), correctAnswers(correctAnswers){}

    //! The date the quiz was taken.
    string dateOfQuiz;
    //! Number of correct answers during the quiz.
    int correctAnswers;
};




int main(void)
{
	return 0;
}



void addUser(string ID, string password)
{
    string outfile = "data\\users.txt";
    ofstream output(outfile.c_str(),std::ofstream::app);
    output << ID << " " << encryptPassword(password) << endl;
    output.close();
}
