#ifndef QUIZ_H_INCLUDED
#define QUIZ_H_INCLUDED

#include <iostream>
#include <stdlib.h>
#include <fstream>
#include <sstream>
#include <string.h>
#include <vector>
#include <iomanip>
#include <ctime>
#include <time.h>
#include <algorithm>    // needed for random_shuffle

#include "user.h"

#define TRUE 1
#define FALSE 0

using namespace std;

class QuizResult;
class QuizAttempt;
class Question;

class too_few_questions {};


//! A function to fill up the questionBank.
/*!
		Encrypts the password by modifying each character in the string, as well as adding extra characters.
*/
int fillQuestionBank(void);

//! QuizResult class
/********************************************//**
Class for a QuizResult. Is generated by a QuizAttempt, and saved to a StudentProfile.
***********************************************/
class QuizResult
{
  public:

    //! Constructor used to generate a QuizResult.
    /*!
        \param dateOfQuiz the date the quiz was taken.
        \param correctAnswers Number of correct answers during the quiz.
    */
    QuizResult(string dateOfQuiz, int correctAnswers):
        dateOfQuiz(dateOfQuiz), correctAnswers(correctAnswers){}

    //! The date the quiz was taken.
    string dateOfQuiz;
    //! Number of correct answers during the quiz.
    int correctAnswers;
};

//! QuizAttempt class
/********************************************//**
Class for a QuizAttempt. Is generated by a student taking a quiz.
***********************************************/
class QuizAttempt
{
  public:

    //! Constructor used to generate a QuizAttempt.
    /*!
        \param *student pointer to the student taking the quiz.
    */
    QuizAttempt(StudentUser *student_user);

    //! Member function which asks the student all 10 questions and records the student's answers.
    /*!

    */
    void runQuiz(void);

    //! Member function which adds 10 random questions from the questionBank vector.
    /*!

    */
    void getQuestions(void);

    //! A member function to save the quiz result to the student's profile.
    /*!

    */
    void saveResultToProfile(void);

  protected:
    //! Pointer to the user taking the quiz.
    StudentUser *student_user;
    //! Vector of pointers to questions.
    vector<Question*> quizQuestions;
    //! Number of questions answered correctly.
    int correctAnswers;
};

//! Question class
/********************************************//**
Class for a Question. Is generated by a QuizAttempt, and saved to a StudentProfile.
***********************************************/
class Question
{
  public:

    //! Constructor used to generate a Question in memory.
    /*!
        \param questionString the text of the question.
        \param correctAnswer Index number of the correct answer inside of the answerChoice vector.
    */
    Question(string questionString, char correctAnswer):
        questionString(questionString), correctAnswer(correctAnswer){}

    //! A member function to add an answerChoice to the question.
    /*!
        \param answer the possible answer to be added.
    */
    void addAnswerChoice(string answer);

    //! A member function used during a QuizAttempt to ask the student this question.
    /*!

    */
    void askQuestion(void);

    //! A member function to check if the answer chosen is correct.
    /*!
        \param answerInput the index number of the answer to check.
        \return TRUE if the answer is correct, FALSE if it is incorrect.
    */
    bool checkAnswer(char answerInput);

    //! A member function to print a question to the screen.
    /*!
        Just calls printToFile, but passes it the console output instead of a file.
    */
    void printToScreen(void);

    //! A member function to print a question to a specified file.
    /*!
        \param &output a pointer to the output file stream to print to.
    */
    void printToFile(ostream &output);

  protected:
    //! The actual question.
    string questionString;
    //! Vector of possible answers to the question.
    vector<string> answerChoice;
    //! Index number of correct answer inside answerString[].
    char correctAnswer;
};





#endif // QUIZ_H_INCLUDED
